<?php
$translate = array(
    'lang' => 'en',
    
    'clubs' => 'Clubs',
    'bars' => 'Bars',
    'restaurants' => 'Restaurants',
    
    'places_and_ratings' => 'Places and ratings',
    'place_type' => 'Place type',
    'shebangs' => 'Shebangs',
    'shebangs_new' => 'Add new shebang',
    'shebangs_delete' => 'Delete this shebang ?',
    'rating' => 'Ratings',
    'rating_types' => 'Rating types',
    'rating_name' => 'Rating name',
    'rating_rate' => 'Overage rate',
    'rating_users_rated' => 'Users rated',
    'interviews' => 'Interviews',
    'interviews_new' => 'Add new interview',
    'interviews_delete' => 'Delete this intervju ?',
    'category' => 'Category',
    'categories' => 'Categories',
    'author' => 'Author',
    'authors' => 'Authors',
    'pages' => 'Pages',
    'pages_new' => 'Add new page',
    'pages_delete' => 'Delete this page ?',
    'is_main_page' => 'Is main page',
    'news' => 'News',
    'news_new' => 'Add new item',
    'news_delete' => 'Delete this news item ?',
    'events' => 'Events',
    'events_new' => 'Add new event',
    'events_delete' => 'Delete this event ?',
    
    'Main picture' => 'Main picture',
    
    'new_shebang' => 'New shebang',
    'new_page' => 'New page',
    'new_news_item' => 'New news item',
    'new_event' => 'New event',
    'new_int' => 'New intervju',
    
    'show_in_frontend' => 'Show in frontend',
    'title' => 'Title',
    'short_descr' => 'Short description',
    'full_text' => 'Full text',
    'text' => 'Text',
    'title' => 'Title',
    
    'Description' => 'Description',
    'News' => 'News',
    'Events' => 'Events',
    'Comments' => 'Comments',
    
    'map' => 'Map',
    'Pictures' => 'Pictures',
    'Main picture' => 'Main picture',
    'Small picture' => 'Small picture',
    'Big picture' => 'Big picture',
    'Add picture' => 'Add new picture',
    'Videos' => 'Videos',
    'Add video' => 'Add new video',
    'Files' => 'Files',
    'File' => 'File',
    'Add file' => 'Add new file',
    
    'filter' => 'Filter',
    'filter_10' => 'Last 10',
    'filter_week' => 'Last week',
    'filter_month' => 'Last month',
    'filter_period' => 'Period',
    'from' => 'From',
    'to' => 'To',
    
    'settings' => 'Settings',
    'users' => 'Users',
    'change_pass' => 'Change password',
    'logout' => 'Logout',
    'err_login' => 'Wrong username or password',
    'user_banned' => 'You are banned',
    
    'login' => 'Login',
    
    'settings' => 'Settings',
    'lang' => 'Language',
    
    'view' => 'View',
    'add' => 'Add',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'close' => 'Close',
    'save' => 'Save',
    'find' => 'Find',
    
    'password' => 'Password',
    'repeat_password' => 'Repeat password',
    'Name' => 'Name',
    'Birthdate' => 'Birthdate',
    'Banned' => 'Banned',
    
    'denied' => 'No rights',
    "The password can not be empty" => 'The password can not be empty', 
    "The min length of password is 5" => 'The min length of password is 5', 
    "The passwords does not match" => 'The passwords does not match', 
    'The password sucefuly changed' => 'The password sucefuly changed', 
    
    'denied' => 'The page "%" denied',
    'dont_exists' => 'The page "%" you was trying to retrieve was moved or doesn’t exists.',
    'back_home' => 'Back home',
    
    'Places' => 'Places',
    'News' => 'News',
    'Events' => 'Events',
    'Interviews' => 'Interviews',
    'People' => 'People',
    'Map' => 'Map',
    'Contacts' => 'Contacts',
    
    'bars_all' => 'All bars',
    'clubs_all' => 'All clubs',
    'restaurants_all' => 'All restaurants',
    
    'rated' => 'You have already rated this parameter',
    
    'cache' => 'Cache (disable to see changes now)'
);
