<?php
$translate = array(
    'lang' => 'ru',
    
    'clubs' => 'Клубы',
    'bars' => 'Бары',
    'restaurants' => 'Рестораны',
    
    'places_and_ratings' => 'Заведения и рейтинг',
    'place_type' => 'Вид заведения',
    'shebangs' => 'Заведения',
    'shebangs_new' => 'Новое заведение',
    'shebangs_delete' => 'Удалить данное заведение ?',
    'rating' => 'Рейтинги',
    'rating_types' => 'Виды рейтинга',
    'rating_name' => 'Название рейтинга',
    'rating_rate' => 'Средняя оценка',
    'rating_users_rated' => 'Пользователей проголосовало',
    'interviews' => 'Интервью',
    'interviews_new' => 'Добавить интервью',
    'interviews_delete' => 'Удалить данное интервью ?',
    'category' => 'Категория',
    'categories' => 'Категории',
    'author' => 'Автор',
    'authors' => 'Авторы',
    'pages' => 'Статические страницы',
    'is_main_page' => 'Страница является главной',
    'pages_new' => 'Добавить новую страницу',
    'pages_delete' => 'Удалить даную страницу ?',
    'news' => 'Новости',
    'news_new' => 'Добавить новость',
    'news_delete' => 'Удалить данную новость ?',
    'events' => 'События',
    'events_new' => 'Создать новое событие',
    'events_delete' => 'Удалить данное событие ?',
    
    'Main picture' => 'Главное изображение',
    
    'new_shebang' => 'Новое заведение',
    'new_page' => 'Новая страница',
    'new_news_item' => 'Новая новость',
    'new_event' => 'Новое событие',
    'new_int' => 'Новое интервью',
    
    'show_in_frontend' => 'Показывать на сайте',
    'title' => 'Заголовок',
    'short_descr' => 'Короткое описание',
    'full_text' => 'Полный текст',
    'text' => 'Текст',
    
    'Description' => 'Описание',
    'News' => 'Обзоры',
    'Events' => 'События',
    'Comments' => 'Комментарии',
    
    'map' => 'Карта',
    'Pictures' => 'Изображения',
    'Main picture' => 'Главное изображение',
    'Small picture' => 'Маленькое изображение',
    'Big picture' => 'Большое изображение',
    'Add picture' => 'Добавить изображение',
    'Videos' => 'Видео',
    'Add video' => 'Добавить видео',
    'Files' => 'Файлы',
    'File' => 'Файл',
    'Add file' => 'Новый файл',
    
    'filter' => 'Фильтр',
    'filter_10' => 'Последние 10',
    'filter_week' => 'Созданные на прошлой неделе',
    'filter_month' => 'Созданные за последний месяц',
    'filter_period' => 'Созданные за период',
    'from' => 'с',
    'to' => 'по',
    
    'settings' => 'Настройки',
    'users' => 'Пользователи',
    'change_pass' => 'Изменить пароль',
    'logout' => 'Выйти',
    'err_login' => 'Неправильный логин либо пароль',
    'user_banned' => 'Вы забанены',
    
    'login' => 'Логин',
    
    'settings' => 'Насройки',
    'lang' => 'Язык интерфейса',
    
    'view' => 'Просмотр',
    'add' => 'Создать',
    'edit' => 'Редактирование',
    'delete' => 'Удалить',
    'close' => 'Закрыть',
    'save' => 'Сохранить',
    'find' => 'Искать',
    
    'password' => 'Пароль',
    'repeat_password' => 'Повторите пароль',
    'Name' => 'Имя',
    'Birthdate' => 'Д.Р.',
    'Banned' => 'Забанен',
    
    'denied' => 'Нехватает прав',
    "The password can not be empty" => 'Пароль не может быть пустым', 
    "The min length of password is 5" => 'Минимальная длинна пароля 5 символов', 
    "The passwords does not match" => 'Пароли должны совпадать', 
    'The password sucefuly changed' => 'Пароль успешно изменён', 
    
    'denied' => 'Недостаточно прав для просмотра страницы "%"',
    'dont_exists' => 'Страница "%" была перемещена, либо её не существует.',
    'back_home' => 'Домой',
    
    'Places' => 'Места',
    'News' => 'Обзоры',
    'Events' => 'События',
    'Interviews' => 'Интервью',
    'People' => 'Люди',
    'Map' => 'Карта',
    'Contacts' => 'Контакты',
    
    'bars_all' => 'Все бары',
    'clubs_all' => 'Все клубы',
    'restaurants_all' => 'Все рестораны',
    
    'rated' => 'Вы уже оценили этот параметр',
    
    'cache' => 'Cache (Если убрать - изменения будут видны сразу)'
);
